version: "3.8"
services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./proxy/nginx/ssl/:/etc/nginx/ssl/:ro
    depends_on:
      - santas-api
      - rabbitmq
    networks:
      - aws-ec2
  rabbitmq:
    image: rabbitmq:3.12.6-management-alpine
    container_name: rabbitmq
    restart: always
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
      - ./rabbitmq/conf.d/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - aws-ec2
  santas-api:
    image: the-goapp-image
    restart: always
    ports:
      - 9545:9545
    env_file:
      - ./.env
    environment:
      - GIN_MODE=release
      - TZ=Asia/Bangkok
    volumes:
      - ./public:/app/go/public
    networks:
      - aws-ec2
    depends_on:
      - rabbitmq
networks:
  aws-ec2:
    name: aws-ec2-bridge
    driver: bridge
